# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a685f60728d8bc4bbe29a6169fc6622509852cae2a30390052e69bc5b1531fa2d0ea4c371ea8dd1d0005f9d32899498a9a6655013007d28cbdb33a828eb9e08

test:
  secret_key_base: 2c1d91cc294ef7f33c969d0439f9ed869d926004fc41b65731198d145959a4d040cac6b5141f1e32f43e3a4681140ed62c4ee8bdc15174773ed094f2b7b657e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
